### ISSUE TITLE
Token substitution in YAML env file

### ISSUE THREAD

**Issue by angloyna** [angloyna/test-conda-bot#24]
I have the following env file:

```yaml
channels:
  - t/$ANACONDA_TOKEN/MYCHANNEL
  - conda-forge
  - anaconda

dependencies:
  - python ==3.7.6
  - myprivatepacakge
```

`ANACONDA_TOKEN` is correctly defined in my bash. But when I run the following, the token is not substituted:

```bash
conda create -y -n test_env
conda activate test_env
conda env update -f test_env.yml
```

I got the following error:

```bash
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org$anaconda_token/MYCHANNEL/linux-64/repodata.json>
Elapsed: -
```

Note that if I substitute `$ANACONDA_TOKEN` by the real token, it works well.

Is that a bug or just a not supported feature?

Related PR: https://github.com/conda/conda/pull/7826
